steps:
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'us-central1-docker.pkg.dev/deep-wave-419401/flask-proj/flaskproject-server', '.']


  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/deep-wave-419401/flaskproject-server:flask-proj', '.' ]
      # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/deep-wave-419401/flaskproject-server:latest' ]
      # Deploy the container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'web-service'
      - '--image=gcr.io/deep-wave-419401/flaskproject-server:us-central1-docker.pkg.dev/deep-wave-419401/flask-proj'
      - '--platform=managed'
      - '--region=REGION'